### ISSUE TITLE
TO-DO #1

### ISSUE THREAD

**Issue by despos** [Youbiquitous/project-renoir#2]
- [ ] Clean up the UI of some views a bit: Add roles, version number in landing
- [ ] Separate products and versions, so that each product can have multiple versions and still be treated as a product
- [ ] Distinguish system and operator users ONLY and use binding roles to product to determine what one can do
- [ ] Add support for Viewer and Contributor roles
- [ ] Add support for TodoList documents
- [ ] Export HTML/PDF
- [ ] Export Word (ideally)
- [ ] Add more descriptive fields to target the structure a "standard" Word doc 
- [ ] Add minimal support for user profile (change of password, change of display name)
- [ ] Let users to reset password
- [ ] Let users to confirm their account and set password autonomously
